// swift-tools-version:6.0
//
// Workspace.swift
@preconcurrency import ProjectDescription

let workspace = Workspace(
    name: "Example",
    projects: [
        "."
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
