// Workspace.swift


@preconcurrency import ProjectDescription


let workspace = Workspace(
    name: "Example",
    projects: [
        "."
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)

