// swift-tools-version:6.0


@preconcurrency
import ProjectDescription


let workspace = Workspace(
    name: "Example",
    projects: [
        "."
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
