// Workspace.swift
import ProjectDescription

let workspace = Workspace(
    name: "Example",
    projects: [
        "Projects/Example/**"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
