//
//  Macro-focused checks on the fixture states (generated by @ReduxState /
//  @ReduxMappedState): real observation for the owned state, and the
//  binding-init / forwarders / conformance for the mapped state.
//

import Testing
import Observation
@testable import TinyRedux


/// Sendable box so the observation `onChange` (a `@Sendable` closure) can flip a flag.
final class Flag: @unchecked Sendable
{
  var value = false
}


// ── @ReduxState: generated init + ReadOnly + REAL observation (no @Observable) ─

@MainActor
@Test
func macroReduxState_generatesAndObserves() async
{
  let s = CounterModuleState(count: 1)          // macro-generated designated init
  #expect(s.readOnly.count == 1)                // macro-generated ReadOnly

  let _: any ReduxState = s                      // Observable conformance added by the macro

  let flag = Flag()
  withObservationTracking
  {
    _ = s.readOnly.count                         // tracks the nested @Observable storage
  }
  onChange:
  {
    flag.value = true
  }

  s.count = 5                                    // forwards to the @Observable storage
  #expect(s.readOnly.count == 5)
  #expect(flag.value)                            // observation fired → owned state IS observable
}


// ── @ReduxMappedState: generated binding-init + forwarders + conformance ──────

@MainActor
@Test
func macroMappedState_generatesAndWritesThrough() async
{
  let p = UserModuleState(firstName: .projected("neo"),   // macro-generated init(_: ReduxBinding…)
                          familyName: .projected("anderson"),
                          isAuthenticated: .projected(false))

  let _: any ReduxMappedState = p                         // conformance written inline + Observable by macro

  #expect(p.readOnly.firstName == "neo")
  #expect(p.readOnly.isAuthenticated == false)

  p.firstName = "thomas"                                  // computed forwarder → ReduxBinding → storage
  p.isAuthenticated = true
  #expect(p.readOnly.firstName == "thomas")
  #expect(p.readOnly.isAuthenticated == true)
}


// ── VERIFY: does a CHILD state observe through the ROOT's ReadOnly chain, with the
//    child NOT marked @Observable (only its @ReduxState nested storage is)? ──────

@MainActor
@Test
func childLinearState_observesThroughRootChain() async
{
  let store = DemoModule.makeStore()
  let flag = Flag()

  withObservationTracking
  {
    _ = store.state.counter.count       // root.ReadOnly → child CounterModuleState → count
  }
  onChange:
  {
    flag.value = true
  }

  store.dispatch(.counter(.increment))  // mutates the child via the lift
  var attempts = 0
  while store.state.counter.count == 0, attempts < 1_000
  {
    await Task.yield()
    attempts += 1
  }

  #expect(store.state.counter.count == 1)
  #expect(flag.value)                   // did the child mutation fire observation through the chain?
}


@MainActor
@Test
func childScatteredLeaf_observesThroughRootChain() async
{
  let store = DemoModule.makeStore()
  let flag = Flag()

  withObservationTracking
  {
    _ = store.state.user.firstName      // root.ReadOnly → app-owned UserState leaf → firstName
  }
  onChange:
  {
    flag.value = true
  }

  store.dispatch(.user(.setFirstName("Ada")))   // mapped reducer writes through the binding → leaf
  var attempts = 0
  while store.state.user.firstName.isEmpty, attempts < 1_000
  {
    await Task.yield()
    attempts += 1
  }

  #expect(store.state.user.firstName == "Ada")
  #expect(flag.value)
}
