//
//  Fixtures for the SubStore layer tests: a `.linear` module (Counter) and a
//  `.scattered` / mapped module (User) composed into a demo root — all states
//  generated by the @ReduxState / @ReduxMappedState macros.
//

import Foundation
@testable import TinyRedux


// ════════════════════════════════════════════════════════════════════════════
// MODULE — Counter (.linear, owned value-backed state)
// ════════════════════════════════════════════════════════════════════════════

@ReduxState
@Observable
@MainActor
final class CounterModuleState: ReduxState
{
  var count: Int

  nonisolated convenience init()
  {
    self.init(count: 0)
  }
}


@ReduxAction
enum CounterModuleActions: ReduxAction
{
  case increment
  case decrement
}


let counterReducer: AnyReduxReducer<CounterModuleState, CounterModuleActions> = .init(id: "counterReducer")
{ context in
  let (state, action) = context.args

  switch action
  {
  case .increment:
    state.count += 1
    return .next
  case .decrement:
    state.count -= 1
    return .next
  }
}


// ════════════════════════════════════════════════════════════════════════════
// APP-OWNED leaves — split storage the mapped module projects onto
// ════════════════════════════════════════════════════════════════════════════

@ReduxState
@Observable
@MainActor
final class UserState: ReduxState
{
  var firstName: String
  var familyName: String

  nonisolated convenience init()
  {
    self.init(firstName: "", familyName: "")
  }
}


@ReduxState
@Observable
@MainActor
final class AuthenticationState: ReduxState
{
  var isAuthenticated: Bool

  nonisolated convenience init()
  {
    self.init(isAuthenticated: false)
  }
}


// ════════════════════════════════════════════════════════════════════════════
// MODULE — User (.scattered, mapped via ReduxBinding) — generated by the macro
// ════════════════════════════════════════════════════════════════════════════

@ReduxMappedState
@MainActor
final class UserModuleState: ReduxMappedState
{
  var firstName: String
  var familyName: String
  var isAuthenticated: Bool
}


extension UserModuleState {
  /// Module mock for previews/tests: real write-through, no root, no stale copies.
  @MainActor
  static func mock(firstName: String = "Mario",
                   familyName: String = "Rossi",
                   isAuthenticated: Bool = false) -> UserModuleState
  {
    UserModuleState(
      firstName: .projected(firstName),
      familyName: .projected(familyName),
      isAuthenticated: .projected(isAuthenticated)
    )
  }
}


@ReduxAction
enum UserModuleActions: ReduxAction
{
  case setFirstName(String)
  case setFamilyName(String)
  case setAuthenticated(Bool)
}


let userReducer: AnyReduxReducer<UserModuleState, UserModuleActions> = .init(id: "userReducer")
{ context in
  let (state, action) = context.args

  switch action
  {
  case .setFirstName(let v):
    state.firstName = v
    return .next
  case .setFamilyName(let v):
    state.familyName = v
    return .next
  case .setAuthenticated(let v):
    state.isAuthenticated = v
    return .next
  }
}


/// Live mock module: reduces locally with the real reducer (interactive previews),
/// and records dispatched actions for assertions.
@MainActor
final class UserModuleMock: ReduxModule
{
  typealias S = UserModuleState
  typealias A = UserModuleActions

  private let _state: UserModuleState
  private(set) var dispatched: [UserModuleActions] = []

  init(_ state: UserModuleState)
  {
    self._state = state
  }

  var state: UserModuleState.ReadOnly { _state.readOnly }

  nonisolated func dispatch(_ actions: UserModuleActions...)
  {
    let captured = actions
    Task { @MainActor in
      for action in captured
      {
        self.dispatched.append(action)
        _ = userReducer.reduce(ReduxReducerContext(self._state, action))
      }
    }
  }
}


// ════════════════════════════════════════════════════════════════════════════
// APP — demo root composing Counter (.linear) + User (.scattered)
// ════════════════════════════════════════════════════════════════════════════

@ReduxState
@Observable
@MainActor
final class DemoAppState: ReduxState
{
  var counter: CounterModuleState
  var user: UserState
  var authentication: AuthenticationState

  nonisolated convenience init()
  {
    self.init(counter: CounterModuleState(),
              user: UserState(),
              authentication: AuthenticationState())
  }
}


@ReduxAction
enum DemoAppActions: ReduxAction
{
  case counter(CounterModuleActions)
  case user(UserModuleActions)
}

extension DemoAppActions {
  var counter: CounterModuleActions? {
    guard case let .counter(a) = self else { return nil }
    return a
  }

  var user: UserModuleActions? {
    guard case let .user(a) = self else { return nil }
    return a
  }
}


// The .scattered mapping closure: (root) -> mapped LS, via per-field ReduxBinding.
let userMapping: @MainActor @Sendable (DemoAppState) -> UserModuleState =
{ app in
  UserModuleState(
    firstName: ReduxBinding {
      app.user.firstName
    } set: {
      app.user.firstName = $0
    },
    familyName: ReduxBinding {
      app.user.familyName
    } set: {
      app.user.familyName = $0
    },
    isAuthenticated: ReduxBinding {
      app.authentication.isAuthenticated
    } set: {
      app.authentication.isAuthenticated = $0
    }
  )
}


// One ReduxModuleMap per module — drives BOTH the reducer lift and the slice.
@MainActor
enum DemoModule
{
  static let counter = ReduxModuleMap<CounterModuleState, CounterModuleActions, DemoAppState, DemoAppActions>
    .linear(state: \.counter,
            action: \.counter,
            toRootAction: DemoAppActions.counter)

  static let user = ReduxModuleMap<UserModuleState, UserModuleActions, DemoAppState, DemoAppActions>
    .scattered(state: userMapping,
               action: \.user,
               toRootAction: DemoAppActions.user)

  static func makeStore() -> ReduxStore<DemoAppState, DemoAppActions>
  {
    ReduxStore(
      initialState: DemoAppState(),
      reducers: [
        AnyReduxReducer(counterReducer, moduleMap: counter),
        AnyReduxReducer(userReducer, moduleMap: user)
      ]
    )
  }
}
